Apps/controleAcesso/urls.py
"""subsTribut URL Configuration

"""
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from django.urls import path

from Apps.controleAcesso.views.gerenciarPermissoes import ajax_content_type
from Apps.controleAcesso.views.gerenciarPermissoes import ajax_permissoes_grupo
from Apps.controleAcesso.views.gerenciarPermissoes import criar_grupo
from Apps.controleAcesso.views.gerenciarPermissoes import criar_permissao
from Apps.controleAcesso.views.gerenciarPermissoes import gerenciar_permissoes
from Apps.controleAcesso.views.usuario import adicionar_usuario
from Apps.controleAcesso.views.usuario import ajax_pesquisar_usuarios
from Apps.controleAcesso.views.usuario import alterar_senha
from Apps.controleAcesso.views.usuario import editar_usuario
from Apps.controleAcesso.views.usuario import gerenciar_usuarios
from Apps.controleAcesso.views.usuario import recuperar_senha

urlpatterns = [
    path('intranet/usuarios/adicionar', adicionar_usuario, name='adicionar_usuario'),
    path('intranet/usuarios', gerenciar_usuarios, name='gerenciar_usuarios'),
    path('intranet/usuarios/editar/<int:usuario_id>', editar_usuario, name='editar_usuario'),
    path('intranet/usuarios/search/ajax', ajax_pesquisar_usuarios, name='ajax_pesquisar_usuarios'),
    path('intranet/gerenciar/permissoes', gerenciar_permissoes, name='gerenciar_permissoes'),
    path('intranet/gerenciar/permissoes/search/ajax/permissoes', ajax_permissoes_grupo, name='ajax_permissoes_grupo'),
    path('intranet/gerenciar/permissoes/search/ajax/content_type', ajax_content_type, name='ajax_content_type'),
    path('intranet/gerenciar/permissoes/criar/permissao', criar_permissao, name='criar_permissao'),
    path('intranet/gerenciar/permissoes/criar/grupo', criar_grupo, name='criar_grupo'),
    path('intranet/usuarios/alterar/senha', alterar_senha, name='alterar_senha'),
    path('intranet/usuarios/recuperar/senha', recuperar_senha, name='recuperar_senha'),
    path('intranet/usuarios/recuperar/senha/enviado',
         PasswordResetDoneView.as_view(template_name='controleAcesso/usuarios/recuperar_senha_enviado.html'),
         name='recuperar_senha_enviado'),
    path('intranet/usuarios/recuperar/senha/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(template_name='controleAcesso/usuarios/recuperar_senha_confirmacao.html'),
         name='recuperar_senha_confirmacao'),
    path('intranet/usuarios/recuperar/senha/concluido',
         PasswordResetCompleteView.as_view(template_name='controleAcesso/usuarios/recuperar_senha_concluido.html'),
         name='password_reset_complete'),
]

intranetPoli/urls.py
"""intranetPoli URL Configuration

The `urlpatterns` list routes URLs to blah. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function blah
    1. Add an import:  from my_app import blah
    2. Add a URL to urlpatterns:  path('', blah.home, name='home')
Class-based blah
    1. Add an import:  from other_app.blah import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('Apps.intranet.urls')),
                  path('controleAcesso/', include('Apps.controleAcesso.urls')),
                  path('st/', include('Apps.subsTribut.urls')),
                  path('assinatura/', include('Apps.assinaturas.urls')),
                  path('catalogos/', include('Apps.catalogos.urls')),
                  path('contabilidade/', include('Apps.resultadoContabil.urls')),
                  path('liberar_desconto/', include('Apps.liberarDesconto.urls')),
                  path('cpd/painel/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "intranetPoli.views.page_not_found_view"
handler403 = "intranetPoli.views.page_access_denied"

Apps/controleAcesso/models/controleAcesso.py
from django.db import models


# Create your models here.
class ControleAcesso(models.Model):
    class Meta:
        managed = False  # No database table creation or deletion  \
        # operations will be performed for this model.

        # default_permissions = ()  # disable "add", "change", "delete"
        # # and "view" default permissions

        verbose_name = 'Controle de Acesso'
        verbose_name_plural = 'Controle de Acessos'

        permissions = [('pode_cadastrar_irpj', 'Pode Cadastrar IRPJ'),
                       ('pode_liberar_desconto', 'Pode Liberar Desconto'),
                       ('pode_acessar_painel_admin', 'Pode Acessar Painel de Admin')]

Apps/controleAcesso/forms/form_usuario.py
from django import forms
from django.contrib.auth.models import Group, User
from django.contrib.auth.password_validation import validate_password, password_validators_help_text_html
from django.core.exceptions import ValidationError

GRUPOS = []
for grupo in Group.objects.all():
    GRUPOS.append((grupo.id, grupo))


class NovoUsuarioForms(forms.Form):
    usuario = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Usuário', 'autocomplete': 'username'}),
                              label='Usuário')
    nome = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Nome'}), required=False, label='Nome')
    sobrenome = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Sobrenome'}), required=False,
                                label='Sobrenome')
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'E-mail', 'autocomplete': 'email'}),
                             label='E-mail')
    senha = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Senha', 'autocomplete': 'new-password'}),
                            label='Senha',
                            help_text=password_validators_help_text_html())
    confirma_senha = forms.CharField(
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirmar Senha', 'autocomplete': 'new-password'}),
        label='Confirmar Senha')
    groups = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs={'placeholder': 'Grupo de Acesso'}),
                                       label='Grupo de Acesso',
                                       choices=GRUPOS)

    adm_intranet = forms.BooleanField(widget=forms.CheckboxInput(),
                                      required=False,
                                      initial=False,
                                      label='Administrador da Intranet')

    def clean(self):
        usuario = self.cleaned_data.get('usuario')
        email = self.cleaned_data.get('email')
        senha = self.cleaned_data.get('senha')
        confirma_senha = self.cleaned_data.get('confirma_senha')

        if User.objects.filter(username=usuario).exists() is True:
            self.add_error('usuario', 'Já existe uma conta com este usuário!')

        if User.objects.filter(email=email).exists() is True:
            self.add_error('email', 'Já existe uma conta com este email!')

        if senha != confirma_senha:
            self.add_error('confirma_senha', 'As senhas não coincidem!')
        elif senha is not None:
            try:
                validate_password(senha)
            except ValidationError as error:
                for erro in error:
                    self.add_error('senha', erro)
        return self.cleaned_data


class AtualizaUsuarioForms(forms.ModelForm):
    class Meta:
        model = User
        fields = ('id', 'username', 'groups', 'email', 'first_name', 'last_name', 'is_staff')
        labels = {
            'username': 'Usuário',
            'email': 'E-mail',
            'first_name': 'Nome',
            'last_name': 'Sobrenome',
            'is_staff': 'Administrador da Intranet',
            'groups': 'Grupos'
        }
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Usuário', 'readonly': True}),
            'email': forms.EmailInput(attrs={'placeholder': 'E-mail'}),
            'first_name': forms.TextInput(attrs={'placeholder': 'Nome'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Sobrenome'}),
            'groups': forms.SelectMultiple(attrs={'placeholder': 'Grupos'})
        }

    def __init__(self, user, *args, **kwargs):
        super(AtualizaUsuarioForms, self).__init__(*args, **kwargs)
        self.user = user

    def clean_groups(self):
        grupos = self.cleaned_data.get('groups')
        if len(grupos) == 0:
            self.add_error('groups', 'Pelo menos 1 grupo deve ser selecionado!')

        return grupos if self.user.has_perm('auth.change_user') else self.user.groups.all()


def clean_email(self):
    email = self.cleaned_data.get('email')
    if email == '':
        self.add_error('email', 'Campo email não pode ser vazio!')
    return email

Apps/controleAcesso/views/gerenciarPermissoes.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, Permission, ContentType
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

from intranetPoli.decorators import verificar_permissoes


@login_required
@verificar_permissoes(permissoes_exigidas=['controleAcesso.view_controleacesso'])
def gerenciar_permissoes(request):
    contexto = {"title": 'Gerenciar Permissões',
                'grupos': Group.objects.all()}
    if request.method == 'POST':
        if request.user.has_perm('controleAcesso.change_controleacesso'):
            grupo = get_object_or_404(Group, pk=request.POST['selecionar_grupo'])
            grupo.permissions.set(Permission.objects.filter(pk__in=request.POST.getlist('selecionar_permissoes')))
            contexto['id_grupo'] = grupo.pk
        else:
            messages.error(request, f"Você não possui as permissões necessárias para esta operação. "
                                    f"Caso precise deste acesso, entre em contato com o Departamento de Informática da Matriz.")
    return render(request, 'controleAcesso/permissoes/gerenciar_permissoes.html', context=contexto)


@login_required
@verificar_permissoes(permissoes_exigidas=['controleAcesso.view_controleacesso'])
def ajax_permissoes_grupo(request):
    filtro = False
    if request.is_ajax():
        grupo = get_object_or_404(Group, pk=request.GET['grupo_id'])
        permissoes_grupo = False
        if grupo:
            permissoes_grupo = [permissao.pk for permissao in grupo.permissions.all()]
        permissoes = []
        for permissao in Permission.objects.all():
            nome = str(permissao).split(' | ')
            permissoes.append({'id': permissao.pk,
                               'nome': f'{nome[1]} | {nome[2]}'})
        filtro = {'permissoes_grupo': permissoes_grupo,
                  'permissoes': sorted(permissoes, key=lambda perm: perm['nome'])}
    return JsonResponse(filtro)


@login_required
@verificar_permissoes(permissoes_exigidas=['controleAcesso.view_controleacesso'])
def ajax_content_type(request):
    filtro = False
    if request.is_ajax():
        content_types = []
        for content_type in ContentType.objects.all():
            content_types.append({'content_type_id': content_type.pk,
                                  'nome': str(content_type)})
        content_types = sorted(content_types, key=lambda content_type: content_type['nome'])
        filtro = {'content_types': content_types}
    return JsonResponse(filtro)


@login_required
def criar_permissao(request):
    contexto = {"title": 'Gerenciar Permissões',
               'grupos': Group.objects.all()}
    if request.method == 'POST' and request.user.has_perm('controleAcesso.add_controleacesso'):
        contexto['id_grupo'] = int(request.POST['id_grupo'])
        content_type = ContentType.objects.get(pk=request.POST['modelo_selecionado'])
        codinome = request.POST['permissao_nome'].lower().replace(' ', '_')
        if Permission.objects.filter(name=request.POST['permissao_nome']).exists():
            messages.error(request,
                           f'Permissão "{Permission.objects.filter(name=request.POST["permissao_nome"])[0]}" já exise!')
        else:
            try:
                nova_permissao = Permission.objects.create(content_type=content_type,
                                                           name=request.POST['permissao_nome'],
                                                           codename=codinome)
            except Exception as err:
                messages.error(request, f'Erro ao criar permissão: {request.POST["permissao_nome"]}\n{err}')
            else:
                Group.objects.get(pk=request.POST['id_grupo']).permissions.add(nova_permissao)
                nome = str(nova_permissao).split(' | ')
                contexto['permissao'] = {'id': nova_permissao.pk, 'nome': f'{nome[1]} | {nome[2]}'}
    else:
        messages.error(request, f"<p> Você não tem acesso à página ou operação que esta tentando acessar.</p>"
                                f"<p> Caso precise de ter acesso a esta página, contate o Departamento de Informática da Matriz</p>",
                       extra_tags='safe')
    return render(request, 'controleAcesso/permissoes/gerenciar_permissoes.html', context=contexto)


@login_required
def criar_grupo(request):
    contexto = {"title": 'Gerenciar Permissões'}
    if request.method == 'POST' and request.user.has_perm('controleAcesso.add_controleacesso'):
        if Group.objects.filter(name=request.POST['grupo_nome']).exists():
            messages.error(request,
                           f'Grupo "{Group.objects.filter(name=request.POST["grupo_nome"])[0]}" já exise!')
        else:
            try:
                novo_grupo = Group.objects.create(name=request.POST['grupo_nome'])
            except Exception as err:
                messages.error(request, f'Erro ao criar grupo: {request.POST["grupo_nome"]}\n{err}')
            else:
                contexto['id_grupo'] = int(novo_grupo.pk)
    else:
        messages.error(request, f"<p> Você não tem acesso à página ou operação que esta tentando acessar.</p>"
                                f"<p> Caso precise de ter acesso a esta página, contate o Departamento de Informática da Matriz</p>",
                       extra_tags='safe')
    contexto['grupos'] = Group.objects.all()
    return render(request, 'controleAcesso/permissoes/gerenciar_permissoes.html', context=contexto)

templates/controleAcesso/usuarios/adicionar_usuario.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
    <link href="{% static 'controleAcesso/css/usuario.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'gerenciar_usuarios' %}">Gerenciar Usuários</a></li>
    <li class="breadcrumb-item active" aria-current="page">Cadastro de Usuário</li>
{% endblock %}

{% block content %}
    <h1>Adicionar Usuário</h1>
    <div class="mb-4" id="usuario">
        <form action="{% url 'adicionar_usuario' %}" method="post" class="needs-validation" novalidate
              id="cadastro-usuario-id">
            {% csrf_token %}
            <div class="row">
                <div class="col card card-custom">
                    <h6 class="mt-2">Dados da Conta</h6>
                    <div class="form-floating mb-2">
                        {% if form.usuario.errors %}
                            {{ form.usuario|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.usuario|add_class:'form-control' }}
                        {% endif %}
                        <label for="{{ form.usuario.id_for_label }}">
                            {{ form.usuario.label }}{% if form.usuario.field.required %}
                                <span class="required">*</span>{% endif %}</label>
                        <div class="invalid-feedback">
                            {{ form.usuario.errors }}
                        </div>
                    </div> <!-- Usuário -->
                    <div class="form-floating mb-2">
                        {% if form.senha.errors %}
                            {{ form.senha|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.senha|add_class:'form-control' }}
                        {% endif %}
                        <label for="{{ form.senha.id_for_label }}">
                            {{ form.senha.label }}{% if form.senha.field.required %}
                                <span class="required">*</span>{% endif %}</label>
                        <div class="invalid-feedback">
                            {{ form.senha.errors }}
                        </div>
                    </div> <!-- Senha -->
                    <div class="form-floating mb-2">
                        {% if form.confirma_senha.errors %}
                            {{ form.confirma_senha|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.confirma_senha|add_class:'form-control' }}
                        {% endif %}
                        <label for="{{ form.confirma_senha.id_for_label }}">
                            {{ form.confirma_senha.label }}{% if form.confirma_senha.field.required %}
                                <span class="required">*</span>{% endif %}</label>
                        <div class="invalid-feedback">
                            {{ form.confirma_senha.errors }}
                        </div>
                    </div> <!-- Confirmar Senha -->
                </div>
                <div class="col card card-custom ms-2">
                    <h6 class="mt-2">Dados Pessoais</h6>
                    <div class="form-floating mb-2">
                        {% if form.email.errors %}
                            {{ form.email|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.email|add_class:'form-control' }}
                        {% endif %}
                        <label for="{{ form.email.id_for_label }}">
                            {{ form.email.label }} <span class="required">*</span></label>
                        <div class="invalid-feedback">
                            {{ form.email.errors }}
                        </div>
                    </div> <!-- Email -->
                    <div class="form-floating mb-2">
                        {% if form.nome.errors %}
                            {{ form.nome|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.nome|add_class:'form-control' }}
                        {% endif %}
                        <label for="{{ form.nome.id_for_label }}">
                            {{ form.nome.label }}{% if form.nome.field.required %}
                                <span class="required">*</span>{% endif %}</label>
                        <div class="invalid-feedback">
                            {{ form.nome.errors }}
                        </div>
                    </div> <!-- Primeiro Nome -->
                    <div class="form-floating mb-2">
                        {% if form.sobrenome.errors %}
                            {{ form.sobrenome|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.sobrenome|add_class:'form-control' }}
                        {% endif %}
                        <label for="{{ form.sobrenome.id_for_label }}">
                            {{ form.sobrenome.label }}{% if form.sobrenome.field.required %}
                                <span class="required">*</span>{% endif %}</label>
                        <div class="invalid-feedback">
                            {{ form.sobrenome.errors }}
                        </div>
                    </div> <!-- Sobrenome -->
                </div>
                <div class="col card card-custom ms-2">
                    <h6 class="mt-2">Acesso</h6>
                    <div class="form-check form-switch mb-2">
                        {% if form.adm_intranet.errors %}
                            {{ form.adm_intranet|add_class:"form-check-input is-invalid" }}
                        {% else %}
                            {{ form.adm_intranet|add_class:"form-check-input" }}
                        {% endif %}
                        <label class="form-check-label" for={{ form.adm_intranet.id_for_label }}>
                            {{ form.adm_intranet.label }}{% if form.adm_intranet.field.required %}
                                <span class="required">*</span>{% endif %}
                        </label>
                        <div class="invalid-feedback">
                            {{ form.adm_intranet.errors }}
                        </div>
                    </div> <!-- Acessar Painel ADM -->
                    <div class="mb-2">
                        <label for="{{ form.groups.id_for_label }}">
                            {{ form.groups.label }}{% if form.groups.field.required %}
                                <span class="required">*</span>{% endif %}
                        </label>
                        {% if form.groups.errors %}
                            {{ form.groups|add_class:'form-select is-invalid' }}
                        {% else %}
                            {{ form.groups|add_class:'form-select' }}
                        {% endif %}
                        <div class="invalid-feedback">
                            {{ form.groups.errors }}
                        </div>

                    </div> <!-- Grupo de Acesso -->
                </div>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <a href="{% url 'gerenciar_usuarios' %}" class="btn btn-info">Voltar</a>
                <a href="{% url 'adicionar_usuario' %}" class="btn btn-warning">Limpar</a>
                <button type="submit" class="btn btn-success" data-bs-toggle="tooltip">Salvar</button>
            </div>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#id_groups').select2({
                theme: 'classic'
            });
        })
    </script>
    <script>
        $(document).ready(function () {
            $("#id_senha").tooltip({
                title: "{{ form.senha.help_text }}",
                placement: "right",
                trigger: 'manual',
                html: true,
                template: '<div class="tooltip" role="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner border"></div></div>'
            })
        })
    </script>
    <script>
        $("#id_senha").focusin(function () {
            $(this).tooltip('show')
        })

        $("#id_senha").focusout(function () {
            $(this).tooltip('hide')
        })
    </script>

    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
{% endblock %}

templates/controleAcesso/usuarios/editar_usuario.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
    <link href="{% static 'controleAcesso/css/usuario.css' %}" rel="stylesheet" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

{% block breadcrumb %}
    {% if perms.auth %}
        <li class="breadcrumb-item"><a href="{% url 'gerenciar_usuarios' %}">Gerenciar Usuários</a></li>
    {% endif %}
    <li class="breadcrumb-item active" aria-current="page">Editar Usuário: {# Colocar Nome do Usuário #}</li>
{% endblock %}

{% block content %}
    <h1>Editar Usuário</h1>
    {% include 'partials/_alertas.html' %}
    <div class="mb-4" id="editar_usuario">
        <form action="{% url 'editar_usuario' usuario_id %}" method="post" class="needs-validation" novalidate
              id="editar-usuario-form">
            {% csrf_token %}
            <div class="row">
                <div class="col card card-custom">
                    <h6 class="mt-2">Dados da Conta</h6>
                    <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                    <div class="mb-2">
                        {% if form.username.errors %}
                            {{ form.username|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.username|add_class:'form-control' }}
                        {% endif %}
                        <div class="invalid-feedback">
                            {{ form.username.errors }}
                        </div>
                    </div> <!-- Usuário -->
                </div>
                <div class="col card card-custom ms-2">
                    <h6 class="mt-2">Dados Pessoais</h6>
                    <div class="form-floating mb-2">
                        {% if form.email.errors %}
                            {{ form.email|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.email|add_class:'form-control' }}
                        {% endif %}
                        <label for="{{ form.email.id_for_label }}">
                            {{ form.email.label }} <span class="required">*</span></label>
                        <div class="invalid-feedback">
                            {{ form.email.errors }}
                        </div>
                    </div> <!-- Email -->
                    <div class="form-floating mb-2">
                        {% if form.first_name.errors %}
                            {{ form.first_name|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.first_name|add_class:'form-control' }}
                        {% endif %}
                        <label for="{{ form.first_name.id_for_label }}">
                            {{ form.first_name.label }}{% if form.first_name.field.required %}
                                <span class="required">*</span>{% endif %}</label>
                        <div class="invalid-feedback">
                            {{ form.first_name.errors }}
                        </div>
                    </div> <!-- Primeiro Nome -->
                    <div class="form-floating mb-2">
                        {% if form.last_name.errors %}
                            {{ form.last_name|add_class:'form-control is-invalid' }}
                        {% else %}
                            {{ form.last_name|add_class:'form-control' }}
                        {% endif %}
                        <label for="{{ form.last_name.id_for_label }}">
                            {{ form.last_name.label }}{% if form.last_name.field.required %}
                                <span class="required">*</span>{% endif %}</label>
                        <div class="invalid-feedback">
                            {{ form.last_name.errors }}
                        </div>
                    </div> <!-- Sobrenome -->
                </div>
                {% if perms.auth.change_user %}
                    <div class="col card card-custom ms-2">
                        <h6 class="mt-2">Acesso</h6>
                        <div class="form-check form-switch mb-2">
                            {% if form.is_staff.errors %}
                                {{ form.is_staff|add_class:"form-check-input is-invalid" }}
                            {% else %}
                                {{ form.is_staff|add_class:"form-check-input" }}
                            {% endif %}
                            <label class="form-check-label" for={{ form.is_staff.id_for_label }}>
                                {{ form.is_staff.label }}{% if form.is_staff.field.required %}
                                    <span class="required">*</span>{% endif %}
                            </label>
                            <div class="invalid-feedback">
                                {{ form.is_staff.errors }}
                            </div>
                        </div>

                        <div class="mb-2">
                            <label for="{{ form.groups.id_for_label }}">
                                {{ form.groups.label }}{% if form.groups.field.required %}
                                    <span class="required">*</span>{% endif %}
                            </label>
                            {% if form.groups.errors %}
                                {{ form.groups|add_class:'form-select is-invalid' }}
                            {% else %}
                                {{ form.groups|add_class:'form-select' }}
                            {% endif %}
                            <div class="invalid-feedback">
                                {{ form.groups.errors }}
                            </div>

                        </div> <!-- Grupo de Acesso -->

                    </div>
                {% endif %}
            </div>
            <div class="d-flex justify-content-between mt-4">
                {% if perms.auth %}
                    <a href="{% url 'gerenciar_usuarios' %}" class="btn btn-info">Voltar</a>
                {% else %}
                    <a href="{% url 'pagina_inicial' %}" class="btn btn-info">Voltar</a>
                {% endif %}

                <button type="submit" class="btn btn-success" data-bs-toggle="tooltip">Salvar</button>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('#id_groups').select2({
                theme: 'classic'
            });
        })
    </script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
{% endblock %}

templates/controleAcesso/usuarios/recuperar_senha_concluido.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <link href="{% static 'controleAcesso/css/usuario.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <h1>Recuperação de Senha Concluído!</h1>
    <div class="mb-4 w-50" id="usuario">
        <div class="row">
            <div class="col card card-custom">
                <div class="mb-2 mt-3">
                    <p>Sua senha foi alterada com sucesso. Agora você pode acessar a intranet novamente.</p>
                </div>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <a href="{% url 'pagina_inicial' %}" class="btn btn-primary">Página Inicial</a>
            </div>
        </div>
    </div>
{% endblock %}