Apps/assinaturas/urls.py
from django.urls import path

from Apps.assinaturas.views.assinaturas_email import assinaturas_email
from Apps.assinaturas.views.assinaturas_email import criar_assinatura
from Apps.assinaturas.views.assinaturas_email import editar_assinatura
from Apps.assinaturas.views.assinaturas_email import visualizar_assinatura
from Apps.assinaturas.views.assinaturas_email import tutoriais

urlpatterns = [
    path('', assinaturas_email, name='assinaturas_email'),
    path('criar', criar_assinatura, name='criar_assinatura'),
    path('editar/<int:assinatura_id>', editar_assinatura, name='editar_assinatura'),
    path('visualizar', visualizar_assinatura, name='visualizar_assinatura'),
    path('tutoriais/<str:programa_email>', tutoriais, name='tutoriais'),
]

assinatura/assinaturas/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('criar/assinatura', criar_assinatura, name='criar_assinatura'),
    path('visualizar/assinatura', visualizar_assinatura, name='visualizar_assinatura'),
    path('pesquisar/assinatura/', pesquisar_assinatura, name='pesquisar_assinatura')
]

intranetPoli/urls.py
"""intranetPoli URL Configuration

The `urlpatterns` list routes URLs to blah. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function blah
    1. Add an import:  from my_app import blah
    2. Add a URL to urlpatterns:  path('', blah.home, name='home')
Class-based blah
    1. Add an import:  from other_app.blah import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('', include('Apps.intranet.urls')),
                  path('controleAcesso/', include('Apps.controleAcesso.urls')),
                  path('st/', include('Apps.subsTribut.urls')),
                  path('assinatura/', include('Apps.assinaturas.urls')),
                  path('catalogos/', include('Apps.catalogos.urls')),
                  path('contabilidade/', include('Apps.resultadoContabil.urls')),
                  path('liberar_desconto/', include('Apps.liberarDesconto.urls')),
                  path('cpd/painel/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "intranetPoli.views.page_not_found_view"
handler403 = "intranetPoli.views.page_access_denied"

Apps/assinaturas/models.py
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.
phone_regex = RegexValidator(regex=r'^\(\d{2}\)\s\d{4}\-\d{4}$',
                             message="Telefone deve ser no formato: '(00) 0000-0000'.")

alphanumeric_regex = RegexValidator(regex='^[0-9A-Za-zÀ-ÖØ-öø-ÿ .]*$', message="Digite apenas Letras ou Números!")


class Assinatura(models.Model):
    nome = models.CharField(max_length=100, unique=True, validators=[alphanumeric_regex])
    departamento = models.CharField(max_length=100, validators=[alphanumeric_regex])
    fone = models.CharField(max_length=17, validators=[phone_regex])
    ramal = models.CharField(max_length=4)

    def __str__(self):
        return self.nome

Apps/assinaturas/models/assinaturas_email.py
from django.core.validators import RegexValidator
from django.db import models, connection

# Create your models here.
phone_regex = RegexValidator(regex=r'^\(\d{2}\)\s\d{4}\-\d{4}$',
                             message="Telefone deve ser no formato: '(00) 0000-0000'.")

alphanumeric_regex = RegexValidator(regex='^[0-9A-Za-zÀ-ÖØ-öø-ÿ .]*$', message="Digite apenas Letras ou Números!")


class Assinatura(models.Model):
    class Meta:
        verbose_name = 'Assinatura de Email'
        verbose_name_plural = 'Assinaturas de Email'
    CIDADES_CHOICES = []
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT CONCAT(parempr.desc_sigla_empresa, CONCAT(' - ', parempr.nome_uf_empresa)) from DR.par_empresas parempr, DR.par_entidades_vw parentd where parempr.numr_cgc_empresa = parentd.numr_cgc AND parentd.nome_razao_social LIKE 'POLIPECAS DIST%' order by parempr.desc_sigla_empresa;")
        CIDADES_CHOICES = [(empresa[0], empresa[0]) for empresa in cursor.fetchall()]

    codigo_usuario = models.IntegerField(unique=True, blank=True, null=True)
    nome = models.CharField(max_length=100, unique=True, validators=[alphanumeric_regex])
    departamento = models.CharField(max_length=100, validators=[alphanumeric_regex])
    fone = models.CharField(max_length=17, validators=[phone_regex])
    ramal = models.CharField(max_length=4)
    empresa = models.CharField(max_length=100, choices=CIDADES_CHOICES, default="")

    def __str__(self):
        return self.nome

Apps/assinaturas/forms.py
from django import forms
from django.core.validators import RegexValidator
from .models import Assinatura

phone_regex = RegexValidator(regex=r'^\(\d{2}\)\s\d{4}\-\d{4}$',
                             message="Telefone deve ser no formato: '(00) 0000-0000'.")

alfanumerico_regex = RegexValidator(regex='^[0-9A-Za-zÀ-ÖØ-öø-ÿ .]*$', message="Digite apenas Letras ou Números!")


class AssinaturaForms(forms.ModelForm):
    class Meta:
        model = Assinatura
        fields = '__all__'
        labels = {'fone': 'Telefone'}
        widgets = {
            'nome': forms.TextInput(attrs={'placeholder': 'Nome'}),
            'departamento': forms.TextInput(attrs={'placeholder': 'Departamento'}),
            'fone': forms.TextInput(attrs={'placeholder': 'Telefone'}),
            'ramal': forms.TextInput(attrs={'placeholder': 'Ramal'}),

        }

Apps/assinaturas/forms/form_assinaturas.py
from django import forms
from django.core.validators import RegexValidator

from Apps.assinaturas.models import Assinatura

phone_regex = RegexValidator(regex=r'^\(\d{2}\)\s\d{4}\-\d{4}$',
                             message="Telefone deve ser no formato: '(00) 0000-0000'.")

alfanumerico_regex = RegexValidator(regex='^[0-9A-Za-zÀ-ÖØ-öø-ÿ .]*$', message="Digite apenas Letras ou Números!")


class CriaAssinaturaForms(forms.ModelForm):
    class Meta:
        model = Assinatura
        exclude = ('codigo_usuario',)
        labels = {'fone': 'Telefone',
                  'empresa': 'Empresa'}
        widgets = {
            'nome': forms.TextInput(attrs={'placeholder': 'Nome'}),
            'departamento': forms.TextInput(attrs={'placeholder': 'Departamento'}),
            'fone': forms.TextInput(attrs={'placeholder': 'Telefone'}),
            'ramal': forms.TextInput(attrs={'placeholder': 'Ramal'}),
            'empresa': forms.Select(attrs={'class': 'form-select'})
        }

    def clean_nome(self):
        lista_minusculos = [' Da ', ' De ', ' Di ', ' Do ', ' Du ']
        nome = self.cleaned_data.get('nome').lower().title()
        for termo in lista_minusculos:
            nome = nome.replace(termo, termo.lower())
        return nome


class EditarAssinaturaForms(forms.ModelForm):
    class Meta:
        model = Assinatura
        exclude = ('codigo_usuario',)
        labels = {'fone': 'Telefone',
                  'empresa': 'Empresa'}
        widgets = {
            'nome': forms.TextInput(attrs={'placeholder': 'Nome'}),
            'departamento': forms.TextInput(attrs={'placeholder': 'Departamento'}),
            'fone': forms.TextInput(attrs={'placeholder': 'Telefone'}),
            'ramal': forms.TextInput(attrs={'placeholder': 'Ramal'}),
            'empresa': forms.Select(attrs={'class': 'form-select'})
        }

        def clean_nome(self):
            lista_minusculos = [' Da ', ' De ', ' Di ', ' Do ', ' Du ']
            nome = self.cleaned_data.get('nome').lower().title()
            for termo in lista_minusculos:
                nome = nome.replace(termo, termo.lower())
            return nome

Apps/assinaturas/views/assinaturas_email.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from Apps.assinaturas.forms.form_assinaturas import CriaAssinaturaForms, EditarAssinaturaForms
from Apps.assinaturas.models.assinaturas_email import Assinatura
from intranetPoli.decorators import verificar_permissoes


def assinaturas_email(request):
    assinaturas = [{"id": assinatura.id, "nome": assinatura.nome} for assinatura in Assinatura.objects.all()]
    contexto = {"title": 'Assinaturas',
                "assinaturas": assinaturas}

    return render(request, 'assinatura/assinaturas_email.html', context=contexto)


def criar_assinatura(request):
    form = CriaAssinaturaForms()
    assinaturas = [{"id": assinatura.id, "nome": assinatura.nome} for assinatura in Assinatura.objects.all()]
    contexto = {"title": 'Assinaturas',
                "siteAssinatura": {"pagina_criar": 'active'},
                "form": form,
                "assinaturas": assinaturas}

    if request.method == 'POST':
        form = CriaAssinaturaForms(request.POST)
        if form.is_valid():
            form.save()
            query = Assinatura.objects.filter(nome=form.cleaned_data['nome']).get()
            contexto['assinatura'] = query
            contexto['siteAssinatura'] = ''
            return render(request, 'assinatura/visualizar_assinatura.html', contexto)
        contexto['form'] = form
    return render(request, "assinatura/criar_assinatura.html", contexto)


def visualizar_assinatura(request):
    assinaturas = [{"id": assinatura.id, "nome": assinatura.nome} for assinatura in Assinatura.objects.all()]
    query = Assinatura.objects.filter(pk=request.GET['buscar'])
    if query.exists():
        contexto = {"title": 'Assinaturas',
                    'assinatura': query.get(),
                    "assinaturas": assinaturas}
        return render(request, 'assinatura/visualizar_assinatura.html', contexto)
    else:
        return redirect('assinaturas_email')


@login_required
@verificar_permissoes(['assinaturas.change_assinatura'])
def editar_assinatura(request, assinatura_id):
    assinaturas = [{"id": assinatura.id, "nome": assinatura.nome} for assinatura in Assinatura.objects.all()]
    contexto = {"title": 'Editar Assinaturas',
                "assinatura_id": assinatura_id,
                "assinaturas": assinaturas}

    if request.method == 'GET':
        assinatura = get_object_or_404(Assinatura, pk=assinatura_id)
        form = EditarAssinaturaForms(instance=assinatura)

    elif request.method == 'POST':
        assinatura = get_object_or_404(Assinatura, pk=assinatura_id)
        form = EditarAssinaturaForms(request.POST, request.FILES, instance=assinatura)
        if request.user.is_authenticated and form.is_valid():
            form.save()
            messages.success(request, f'Assinatura {assinatura.nome} editada com sucesso!')
            contexto['title'] = 'Assinatura'
            contexto['assinatura'] = get_object_or_404(Assinatura, pk=assinatura_id)
            return render(request, 'assinatura/visualizar_assinatura.html', context=contexto)

    contexto['form'] = form

    return render(request, "assinatura/editar_assinatura.html", contexto)


def tutoriais(request, programa_email):
    assinaturas = [{"id": assinatura.id, "nome": assinatura.nome} for assinatura in Assinatura.objects.all()]
    contexto = {"title": 'Assinaturas',
                "pagina_tutoriais": 'active',
                "programa_email": programa_email,
                "assinaturas": assinaturas}
    return render(request, f"assinatura/guias/{programa_email}.html", context=contexto)

assinatura/assinaturas/views/criar_assinatura.py
from django.shortcuts import render
from assinaturas.forms import AssinaturaForms


def criar_assinatura(request):
    form = AssinaturaForms()
    contexto = {"pagina_criar": 'active',
                'form': form}
    return render(request, "criar_assinatura.html", contexto)

assinatura/assinaturas/views/index.py
from django.shortcuts import render


# Create your views here.
def index(request):
    pagina_selecionada = {"pagina_guia": 'active'}
    return render(request, 'index.html', pagina_selecionada)

assinatura/assinaturas/views/pesquisar_assinatura.py
from django.http import JsonResponse

from assinaturas.models import Assinatura


def pesquisar_assinatura(request):
    if request.is_ajax():
        term = request.GET.get('term', '')
        query = Assinatura.objects.filter(nome__icontains=term)
        lista_assinaturas = list()
        for assinatura in query:
            lista_assinaturas.append(assinatura.nome)
        return JsonResponse(data=lista_assinaturas, safe=False)

assinatura/assinaturas/views/visualizar_assinatura.py
from django.shortcuts import render, redirect, get_list_or_404
from assinaturas.forms import AssinaturaForms
from assinaturas.models import Assinatura


def visualizar_assinatura(request):
    if request.method == 'POST':
        form = AssinaturaForms(request.POST)
        if form.is_valid():
            form.save()
            query = Assinatura.objects.filter(nome=form['nome'].value()).get()
            contexto = {'assinatura': query}
            return render(request, 'visualizar_assinatura.html', contexto)
        else:
            contexto = {'form': form}
            return render(request, 'criar_assinatura.html', contexto)
    if request.method == 'GET':
        query = Assinatura.objects.filter(nome=request.GET['buscar'])
        if query.exists():
            contexto = {'assinatura': query.get()}
            return render(request, 'visualizar_assinatura.html', contexto)
        else:
            return render(request, 'index.html')
    return redirect('criar_assinatura')

templates/assinatura/assinaturas_email.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
    {% include 'assinatura/partials/_menus.html' %}
{% endblock %}

{% block head %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <link href="{% static 'assinatura/css/assinaturas.css' %}" rel="stylesheet" type="text/css">
    {% block extrahead %}
    {% endblock %}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Assinatura de Email</li>
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between">
        <div class="w-25">
        </div>
        <div class="text-center">
            <h1>Bem Vindo.</h1>
            <p class="lead">Crie sua assinatura acima e depois siga o tutorial de instalação para saber como instalar sua
                assinatura. </p>
            <p class="lead">Caso já tenha criado uma vez, não precisa criar outra! Basta pesquisar no campo de pesquisa
                acima!</p>
        </div>
        <div class="w-25">
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {% block extra_scripts %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function () {
            const url_ajax = $('#pesquisar_assinaturas_id').attr('action')
            $('#pesquisar_assinaturas_id').select2({
                minimumInputLength: 2,
                theme: 'classic',
                selectionCssClass: 'custom-select2',
                dropdownCssClass: 'custom-select2',
                width: 'auto',
            })
        })
        $('#pesquisar_assinaturas_id').on("select2:open", () => {
            document.querySelector(".select2-container--open .select2-search__field").focus()
        })
    </script>

{% endblock %}

templates/assinatura/criar_assinatura.html
{% extends 'assinatura/assinaturas_email.html' %}
{% load static %}
{% load widget_tweaks %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'assinaturas_email' %}">Assinatura de Email</a></li>
    <li class="breadcrumb-item active" aria-current="page">Criar Assinatura</li>
{% endblock %}

{% block content %}
    <h1>Criar Assinatura</h1>
    <section class="container col-4">
        <form action="{% url 'criar_assinatura' %}" method="post">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-floating">
                    {{ field|add_class:'form-control mb-2' }}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                {% for error in field.errors %}
                    <section class="alert alert-danger" role="alert">
                        {{ field.errors }}
                    </section>
                {% endfor %}
            {% endfor %}
            <input class="btn btn-success mb-4" type="submit" value="Criar">
        </form>

    </section>
{% endblock %}

{% block extra_scripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"
            integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw=="
            crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('#id_fone').mask('(00) 0000-0000');
        });
        $(document).ready(function () {
            $('#id_ramal').mask('0000');
        });
    </script>
{% endblock %}

templates/assinatura/editar_assinatura.html
{% extends 'assinatura/assinaturas_email.html' %}
{% load static %}
{% load widget_tweaks %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'assinaturas_email' %}">Assinatura de Email</a></li>
    <li class="breadcrumb-item active" aria-current="page">Editar Assinatura</li>
{% endblock %}

{% block content %}
    <h1>Editar Assinatura</h1>
    {% include 'partials/_alertas.html' %}
    <section class="container col-4">
        <form action="{% url 'editar_assinatura' assinatura_id%}" method="post">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="form-floating">
                    {{ field|add_class:'form-control mb-2' }}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                </div>
                {% for error in field.errors %}
                    <section class="alert alert-danger" role="alert">
                        {{ field.errors }}
                    </section>
                {% endfor %}
            {% endfor %}
{#            <input class="btn btn-success mb-4" type="submit" value="Salvar">#}
            <div class="d-flex justify-content-between mt-4 mb-5">
                <a href="{% url 'assinaturas_email' %}" class="btn btn-info">Voltar</a>
                <a href="{% url 'editar_assinatura' assinatura_id %}" class="btn btn-warning">Limpar</a>
                <button type="submit" class="btn btn-success" data-bs-toggle="tooltip">Salvar</button>
            </div>
        </form>

    </section>
{% endblock %}

{% block extra_scripts %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"
            integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw=="
            crossorigin="anonymous"></script>
    <script>
        $(document).ready(function () {
            $('#id_fone').mask('(00) 0000-0000');
        });
        $(document).ready(function () {
            $('#id_ramal').mask('0000');
        });
    </script>
{% endblock %}

templates/assinatura/visualizar_assinatura.html
{% extends 'assinatura/assinaturas_email.html' %}
{% load static %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'assinaturas_email' %}">Assinatura de Email</a></li>
    <li class="breadcrumb-item active" aria-current="page">Visualizar Assinatura</li>
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between">
        <div id="assinatura-id">
            <table style="font-family: sans-serif">
                <tr>
                    <td style="color:#26a6ff">
                        <strong>{{ assinatura.nome }}</strong><br>
                        {{ assinatura.departamento }}<br>
                        {{ assinatura.empresa }}<br>
                        {{ assinatura.fone }} - Ramal: {{ assinatura.ramal }}<br>
                        <a href="https://www.polipecas.com.br" target="_blank"
                           style="color:#26a6ff">www.polipecas.com.br</a><br>
                        <small>Esta mensagem é confidencial e privilegiada. Caso Você não seja o destinatário, não está
                            autorizado a reproduzir ou divulgar a terceiros o conteúdo e deve apaga-lá.</small><br><br>
                        <a href="https://www.polipecas.com.br" target="_blank">
                            <img src="https://www.polipecas.com.br/images/logo/logo-email.png" alt="Logo.png"
                                 moz-do-not-send="false" border="0">
                        </a><br><br>
                        Acesse nosso site, na opção <strong>Portal do Cliente</strong>, baixe
                        suas notas fiscais, boletos, solicite renegociação de dividas entre outras opções.<br>
                    </td>
                </tr>
            </table>
        </div>
        <div class="row">
            <div class="form-check col">
                <input class="form-check-input" type="checkbox" value="" id="check_portal_cliente_id">
                <label class="form-check-label" for="portal_cliente_id">
                    Adicionar recado sobre Portal do Cliente
                </label>
            </div> <!-- Portal do Cliente -->
            <div class="col">
                <label class="form-label">Outlook?</label>
                <div class="form-check">
                    <input class="form-check-input" type="radio" value="1" id="radio_outlook_sim_id"
                           name="radio_outlook">
                    <label class="form-check-label" for="radio_outlook_id">
                        Sim
                    </label>
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="radio" value="0" id="radio_outlook_nao_id"
                           name="radio_outlook" checked>
                    <label class="form-check-label" for="radio_outlook_id">
                        Não
                    </label>
                </div>
            </div> <!-- Outlook - Sim ou Não? -->
        </div>
    </div>

    <div class="d-flex justify-content-between mt-5 mb-4">
        <a class="btn btn-primary" href="#" id="donwload-link" onclick="myFunction()">Baixar Assinatura</a>
        {% if user.is_authenticated %}
            <a class="btn btn-success" href="{% url 'editar_assinatura' assinatura.id %}">Editar</a>
        {% endif %}
        <a href="{% url 'assinaturas_email' %}" class="btn btn-info">Voltar</a>
    </div>
    {#    <div class="mt-5 mb-4">#}
    {#        <a class="btn btn-primary" href="#" id="donwload-link" onclick="myFunction()">Baixar Assinatura</a>#}
    {#        <div class="row">#}
    {#            <a class="btn btn-info" href="{% url 'editar_assinatura' assinatura.id %}">Editar</a>#}
    {#        </div>#}
    {#    </div>#}

{% endblock %}

{% block extra_scripts %}
    <script>
        $("#check_portal_cliente_id").on('click', function () {
            $("#portal_cliente_id").toggle(this.checkd)
        })
    </script>
    <script>
        function myFunction() {
            const inicio_HTML = '<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"></head><body>'
            const fim_HTML = '</body></html>'
            let assinatura = document.getElementById("assinatura-id").innerHTML
            assinatura = inicio_HTML + assinatura + fim_HTML
            let nome = "{{ assinatura.nome}}"
            nome = nome.replaceAll(' ', '')
            let formato
            radio_selecionado = $('input[name=radio_outlook]:checked')
            if (radio_selecionado.val() === "1") {
                formato = 'htm'
            } else {
                formato = 'html'
            }
            download(assinatura, nome, formato)
        }

        function download(assinatura, nome_do_arquivo, tipo_de_arquivo) {
            const link = document.getElementById("donwload-link");
            const arquivo = new Blob([assinatura], {type: tipo_de_arquivo});
            const nome_arquivo_com_extensao = nome_do_arquivo + "." + tipo_de_arquivo;
            link.href = URL.createObjectURL(arquivo);
            link.download = nome_arquivo_com_extensao
        }
    </script>
{% endblock %}